- README.md
> Little fix to README

- platform/mac/Rtt_MacPlatform.mm
- platform/windows/Corona.Native.Library.Win32/Rtt/Rtt_WinPlatform.cpp
This will allow you to change the window width/height in code by passing a table with either `width` or/and `height` values
> Added new native.setProperty() named "windowSize" for MacOS

- platform/mac/CoronaConsole/CoronaConsole/ConsoleWindowController.mm
> macOS: Changed time to military style in console

- README.md
Added more popular games to examples. Also, provided an external link to Wikipedia so new users can see more example games.
> Added new example games and external link

- platform/windows/Corona.Simulator/Simulator.rc
Didn't remove unused strings just in case
To avoid GitHub warning "We’ve detected the file encoding as ISO-8859-1. When you commit changes we will transcode it to UTF-8." tried to save locally but failed anyway.
> Windows/Sim: Rebranding, updated messages and links

- CONTRIBUTING.md
- README.md
Added Discord and forums links to README
Added text editor packages to README
Changed Slack to Discord invite on CONTRIBUTING
> Added text editors and new community links

- platform/android/sdk/src/com/ansca/corona/CoronaWebView.java
- platform/iphone/Rtt_IPhoneWebViewObject.h
- platform/iphone/Rtt_IPhoneWebViewObject.mm
This allows setNativeProperty for the webView
> Lazy web view

- README.md
Added link to Solar2DTux and Solar2D Plugins marketplace.
Made small changes to the benefits of using Solar2D.
> Added link to Solar2DTux

- platform/resources/CoronaBuilderPluginCollector.lua
Added PluginCollectorSolar2DMarketplaceDirectory
> Update CoronaBuilderPluginCollector.lua with PluginCollectorSolar2DMarketplaceDirectory

- tools/CoronaBuilder/CoronaBuilder-Info.plist
- tools/GHAction/process_sources.sh
> macOS: fixing Simulator version not updating

- librtt/Display/Rtt_SpriteObject.cpp
- librtt/Display/Rtt_SpriteObject.h
This is before the commit:
https://user-images.githubusercontent.com/5722355/115132619-2ce6af00-9fd8-11eb-87e6-757b8eac94ea.mp4
And this is after:
https://user-images.githubusercontent.com/5722355/115132627-42f46f80-9fd8-11eb-928d-895a3f58e8c3.mp4
> Core: Fix timeScale transition issues on SpriteSheets

- platform/resources/shell.lua
Correcting "whilde" to "while".
> Fix typo in shell.lua

- CMakeLists.txt
- CMakeSettings.json
- platform/mac/LinuxAppBuildController.mm
- platform/mac/ratatouille.xcodeproj/project.pbxproj
- platform/resources/linuxPackageApp.lua
- platform/shared/Rtt_LinuxAppPackager.cpp
- platform/shared/Rtt_WebAppPackager.cpp
- platform/windows/Corona.Simulator/Simulator.rc
This branch fixes Linux App Builder on Windows and Linux Simulators.
> Porting linux builder to windows

- README.md
> Updated docs link to https://

- platform/mac/IOSAppBuildController.mm
- platform/mac/TVOSAppBuildController.mm
- plugins/README.md
Updated links for daily builds in error messages shown in macOS
Updated dead links for Xcode requirements
Updated http:// links to https://
Rebranding for some error messages if not all
Updated links and instructions for plugins section
> Updated links and instructions, rebranding of error messages

- platform/android/sdk/src/com/ansca/corona/Controller.java
Mainly aimed at fixing display.capture({saveToPhotoLibrary=true}) but the workaround should work with other APIs that uses saveBitmap(bitmap, quality,  filePathName)
> Android: Fix for Android 10 to save to Camera Roll

- platform/linux/src/Rtt_LinuxConsoleApp.cpp
- platform/linux/src/Rtt_LinuxConsolePlatform.cpp
- platform/linux/src/Rtt_LinuxContext.cpp
- platform/linux/src/Rtt_LinuxContext.h
- platform/linux/src/Rtt_LinuxDialog.cpp
- platform/linux/src/Rtt_LinuxDialog.h
- platform/linux/src/Rtt_LinuxDialogBuild.cpp
- platform/linux/src/Rtt_LinuxPlatform.cpp
It should fix the Issue #379.
Tested using "plugin.bit".
> Plugins broken in snap version issue 379

- platform/resources/CoronaBuilderPluginCollector.lua
Used for plugin resources, plan to use for mediation for custom IronSource plugin to start but have future ideas
> Add Solar2d Marketplace Resource Collector

- platform/apple/Rtt_AppleKeyServices.mm
- platform/iphone/ratatouille.xcodeproj/project.pbxproj
> CoronaCards: Fix for iOS KeyServices missing

- platform/android/sdk/src/com/ansca/corona/notifications/NotificationServices.java
> Android: Fix for Local Notifications

- platform/android/sdk/src/com/ansca/corona/NativeToJavaBridge.java
> Android: Fix for NavBar height with getSafeAreaInsets

- platform/mac/AndroidAppBuildController.mm
Using "Copy to device and launch" (Android) does not work with aab
> Simulator: Fix copy to device for Android

- .github/workflows/build.yml
This is blocked by actions/runner-images#6718 deployment
> Apple: moving to Xcode 14.2

- platform/android/sdk/src/com/ansca/corona/CoronaActivity.java
- platform/android/sdk/src/com/ansca/corona/SystemMonitor.java
> Android: re-implementing low memory warning

- external/lua-5.1.3/src/loslib.c
> Windows: fixes os.date crashing

- librtt/Core/Rtt_Assert.c
Was working on a project with the newest version of Solar2D and got a crash on my Mac. Was able to prevent the crash by checking if my device is Apple Silicon(arm) and preventing `raise` from being executed.
> MacOS: Prevent Lua Crashes on Apple Silicon

- platform/android/sdk/src/com/ansca/corona/NativeToJavaBridge.java
> Android: Add hasSoftwareKeys to getInfo

- platform/android/sdk/src/com/ansca/corona/CoronaVideoView.java
^Mainly for Https videos
Tested with these sample remote source
https://gist.github.com/jsturgis/3b19447b304616f18657?permalink_comment_id=3864657#gistcomment-3864657
> Android: Fix RemoteSource for VideoViews

- platform/mac/ratatouille.xcodeproj/project.pbxproj
I was having issues building Sim locally(with Xcode) with the new memory API
> Core Maintenance

- platform/mac/CoronaLiveServer/CoronaLiveServer.xcodeproj/project.pbxproj
Forgot to set MACOSX_DEPLOYMENT_TARGET to $(S2D_MIN_VER_MACOS:default=10.13)
> Maintenance 

- tools/CoronaBuilder/BuilderPluginDownloader.lua
> Native: Fixes for iOS Plugin Downloader

- platform/resources/OSXPackageApp.lua
Avoiding using --deep and --entitlements together
fixes #585
> macOS/Sim: fixing code signing for entitlements

- platform/iphone/Rtt_IPhonePlatformBase.mm
- platform/mac/Rtt_MacPlatform.mm
Implemented system.getInfo("reduceMotion"/"reduceTransparency"/"differentiateWithoutColor")
> Added new accessibility settings for iOS, tvOS and MacOS

- platform/android/sdk/AndroidManifest-New.xml
- platform/android/sdk/src/com/ansca/corona/notifications/NotificationServices.java
- platform/android/sdk/src/com/ansca/corona/notifications/OnNotificationReceiverActivity.java
Android 33 requires you launch notifications with an activity
> Android: Notification Fix for Api 33

- .github/workflows/build.yml
- platform/iphone/ratatouille.xcodeproj/project.pbxproj
> CoronaCards + MetalAngle

- platform/android/app/build.gradle.kts
- platform/android/sdk/build.gradle.kts
> Android: removing deprecated armeabi-v7a 

- platform/android/app/build.gradle.kts
- platform/android/sdk/build.gradle.kts
Reverts coronalabs/corona#665
thanks @clang-clang-clang
> Revert "Android: removing deprecated armeabi-v7a "

- platform/iphone/Rtt_IPhoneVideoPlayer.mm
> iOS: fixing video close crash

- .github/workflows/build.yml
Reference:
https://github.com/actions/runner-images/issues/9459
> iOS: Support for Xcode 15.3

- platform/linux/src/NetworkLibrary.cpp
- platform/linux/src/NetworkLibrary.h
- platform/linux/src/NetworkSupport.cpp
- platform/linux/src/NetworkSupport.h
1. Fix the issue where responseHeaders are lost when returning from network.request().
2. Fix the issue where files cannot be uploaded using network.upload().
Here is the test example, It contains a python3 local upload server **app.py** :
[test_network.zip](https://github.com/user-attachments/files/15783524/test_network.zip)
> [Linux] Fixed the network issues.

- platform/android/build.gradle.kts
> Updating Klaxon to 5.5

- .github/workflows/build.yml
Github Added support for Xcode 16.1 Already
https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
> Apple: Xcode 16.1

- platform/resources/tvosPackageApp.lua
Should fix the issues with tvOS Builds described here:
[https://github.com/coronalabs/corona/issues/752](url)
> Fixed XCPrivacy tvOS

- platform/mac/CoronaBuilder.xcodeproj/project.pbxproj
- platform/mac/car.xcodeproj/project.pbxproj
- platform/tvos/ratatouille.xcodeproj/project.pbxproj
- tools/CoronaBuilder/BuilderPluginDownloader.lua
Tested this with demo project in Enterprise repo with iCloud plugin for TvOS
> Native: Support Plugins on Native TvOS

- platform/android/sdk/src/com/ansca/corona/Controller.java
this addresses
https://github.com/coronalabs/corona/issues/775
https://github.com/user-attachments/assets/7a3b2a2e-7911-4212-ba2b-ce40098241eb
> Fixes to Android Recent Apps Crash

- .github/workflows/build.yml
- platform/windows/Build.Tools/CoronaLabsInc.Sign.bat
- platform/windows/Build.Tools/solar2d.json
- platform/windows/README.md
Lets give Azure Trusted Signing a go. Should fix #565
> Windows trusted code signing

- platform/resources/iPhonePackageApp.lua
This adds support for Custom Entitlement and plist via config.lua for Extension which make it much more useful
> iOS: Better Extension Support

- platform/iphone/CoronaViewPrivate.mm
- platform/tvos/ratatouille.xcodeproj/project.pbxproj
TvOS support keyboard events as well, while not used that much for end users of app, super helpful on development on TvOS and especially TvOS Sim
> TvOS: Support Key Events (Helpful for TV Sim)

- platform/resources/iPhonePackageApp.lua
Fixes to some minor Extension signing issues
> iOS: Extension Support Fixes

- platform/linux/src/Rtt_LinuxContainer.h
There is an error when running cmake which is mentioned here:
https://forums.solar2d.com/t/how-i-made-solar2d-works-on-linux/356469/18
or
https://discord.com/channels/721785436195782677/724637134115438714/1365290245767168070
> [Linux] Fix missing header

- platform/android/sdk/AndroidManifest-New.xml
- platform/android/sdk/src/com/ansca/corona/CoronaActivity.java
- platform/android/sdk/src/com/ansca/corona/NativeToJavaBridge.java
- platform/android/sdk/src/com/ansca/corona/purchasing/StoreActivity.java
- platform/android/template/update_manifest.lua
Android 35 fixes:
Fixes for safe space on bottom, address other google warnings, include updates for subrepos
Address issues:  #794, #822
> Android: Maintenance
