- platform/mac/GLView.mm
This bug happened when using the screenshot tool in MacOS. Simply handled it by just ignoring the event when the keyCode = kVK_ANSI_A because this shouldn't even happen in the 'flagsChanged' method.
Steps to reproduce the original bug: Simply add a "key" listener in the main.lua and print the keyName & phase. Start the simulator and create a screenshot with "cmd + shift + 4". Runtime:addEventListener("key", function(event) print(event.keyName, event.phase) end)
> Fixed bug which was causing an unwanted "a" key event.

- librtt/Rtt_LuaProxyVTable.cpp
SpriteObjects functions (setSequence, setFrame, play, pause) where made read-only. This doesn't match the behaviour of DisplayObject functions and limits customisability for the user.
Below is some code to test this behavior, just needs a `local createdSprite = display.newSprite()` call
```
local initialSetSequenceFunction = createdSprite.setSequence
createdSprite.setSequence = function() end
print(initialSetSequenceFunction == createdSprite.setSequence) -- prints false
local initialScaleFunction = createdSprite.scale
createdSprite.scale = function() end
print(initialScaleFunction == createdSprite.scale) -- prints true
```
> Made SpriteObject functions overridable, just like DisplayObject functions

- librtt/Display/Rtt_SpriteObject.cpp
SetFrame() in Rtt_SpriteObject now sets fPlayTime if it's not playing, and fStartTime when it is.
Previously it always just set fStartTime, that caused the sprite to glitch when there's a delay between SetFrame() and Play() executions.
Code to cause the initial bug:
```
local sprite = createSpriteWith1000msPlaytime()
sprite:setFrame(1)
timer.performWithDelay(2000, function()
sprite:play()
end)
```
> Fixed SpriteObject::SetFrame for when sprite is not playing

- librtt/Rtt_Event.cpp
- librtt/Rtt_Event.h
This commit modifies "touch" events so that the event table dispatched now includes "xDelta" and "yDelta" properties, indicating the difference between the touch's current X/Y values and the "xStart" and "yStart" values.
Added as a convenience so that developers won't have to perform these calculations in their touch listeners.
More-or-less copied from the undocumented Runtime "drag" event.
> add xDelta & yDelta properties to touch events

- librtt/Display/Rtt_SpriteObject.cpp
When a frame takes longer than the duration of a full infinite loop sequence, sprites would get stuck.
I modified the for loop to keep iterating until deltaTime is bigger than fTimeArrayCachedNextFrameTime again.
This will also give it a more consistent result, since it can now return an index higher then effectiveNumFrames (same as when not using a 'time' array)
> Fixed a bug in SpriteObject -> GetFrameIndexForDeltaTime()

- platform/android/sdk/src/com/ansca/corona/Controller.java
- platform/android/sdk/src/com/ansca/corona/CoronaActivity.java
- platform/android/template/AndroidManifest.template.xml
- platform/android/template/AndroidManifest.xml
- platform/android/template/update_manifest.lua
This sets the systemUiVisibility even before the splashScreen comes up, avoiding the resize of the corona logo (which normally happens when settings immersiveSticky in main.lua)
For Android devices < 4.4 setting a initialSystemUiVisibility with `immersiveSticky` will automatically fall back to `lowProfile` mode.
Also added View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION flag to immersive & immersiveSticky modes.
This will prevent the resize event on Android which happens when starting the application. The application will immediately have the right dimension.
Without this, a Corona app on a 1920x1080 screen will start at 1776x1080 and resizes to 1920x1080 shortly after starting up (a "resize" event occurs)
With this, a Corona app will immediately start with 1920x1080 as display.pixelWidth & …
> Added initialSystemUiVisibility property to 'android' key in build.settings

- platform/resources/shell.lua
Removed failed to download plugin alert
not needed because there is a print statement
> Removed failed to download plugin alert

- librtt/Display/Rtt_SpriteObject.cpp
- librtt/Display/Rtt_SpriteObject.h
If you set the time scale of an sprite object that is currently playing, it will keep the frame and allow smooth time scale transitions
> Allow to change the timeScale of an active SpriteObject

- platform/shared/Rtt_LinuxAppPackager.cpp
- platform/shared/Rtt_WebAppPackager.cpp
This PR reads the `build.settings` file and applies the `neverStripDebugInfo` setting when building for Linux.
> Apply neverStripDebugInfo setting when building for Linux

- platform/mac/GLView.mm
- platform/mac/Rtt_MacPlatform.mm
- platform/windows/Corona.Native.Library.Win32/Rtt/Rtt_WinInputDeviceManager.h
- platform/windows/Corona.Native.Library.Win32/Rtt/Rtt_WinPlatform.cpp
This Api allows the Solar developer to change the current operating system mouse cursor within their program on Desktop (Mac/Windows) to the cursor style of their choosing.
**Shared cursors**
The following cursors are available on both platforms:
* "crosshair",
* "pointingHand",
* "beam",
* "notAllowed",
* "resizeLeftRight",
* "resizeUpDown",
* "arrow"
**Windows Cursors**
The following cursors are available on Windows only:
* "appStarting",
* "resizeAll",
* "resizeNorthEastSouthWest",
* "resizeNorthWestSouthEast",
* "upArrow",
* "hourglass"
**Mac Cursors**
The following cursors are available on MacOS only:
* "closedHand", 
* "openHand",
* "resizeRight", 
* "resizeLeft",
* "resizeUp", 
* "resizeDown",
* "disappearingItem", 
* "beamHorizontal", 
* "dragLink", 
* "dragCopy", 
* "contextMenu" …
> Added native.setProperty("mouseCursor", cursorName) Api

- platform/android/sdk/src/com/ansca/corona/input/InputHandler.java
This will keep the functionality of not sending repeated "key" events to lua. But allows Android to decrease/increase the volume.
> Allow Android to handle repeated volume button events

- platform/shared/CoronaLiveServer/CoronaLiveServerCore.cpp
SSL Library not initialized before calling SSL CTX new. Resulting in a null CTX.
At some point, the SSL use to be initialized someplace else (maybe with the license check). In any case, currently, the SSL is not initialized before the call to create a new CTX. This results in a null CTX that gets passed to another method and crashes the live server.
> Init SSL Library before calling ctx new.

- .gitmodules
- platform/iphone/AppDelegate.h
- platform/iphone/AutoLinkModules.m
- platform/iphone/CoronaCards/CoronaView.h
- platform/iphone/CoronaCards/CoronaViewController.h
- platform/iphone/CoronaViewControllerPrivate.h
- platform/iphone/CoronaViewControllerPrivate.mm
- platform/iphone/CoronaViewPrivate.h
- platform/iphone/CoronaViewPrivate.mm
- platform/iphone/CoronaViewRuntimeDelegate.mm
- platform/iphone/Rtt_IPhoneGLVideoTexture.mm
- platform/iphone/Rtt_IPhonePlatform.mm
- platform/iphone/Rtt_IPhonePlatformBase.mm
- platform/iphone/Rtt_IPhonePlatformCore.mm
- platform/iphone/Rtt_IPhoneScreenSurface.h
- platform/iphone/Rtt_IPhoneScreenSurface.mm
- platform/iphone/Rtt_IPhoneTimer.h
- platform/iphone/Rtt_IPhoneTimer.mm
- platform/iphone/ratatouille.xcodeproj/project.pbxproj
I have updated a new version of MetalANGLE to make it compatible with Solar2D's code. More details has been sent via email.
This PR also makes MetalANGLE a submodule and a child of Solar2D's iOS Xcode project so they can be built together from source.
NOTE:
- After pulling MetalANGLE via "git submodule update --init --recursive", you need to call "external/metalangle/ios/xcode/fetchDependencies.sh" to fetch MetalANGLE's dependencies. ANGLE's dependencies are not usable as submodules so we have to use a script unfortunately.
> MetalANGLE preliminary integration

- platform/resources/CoronaPListSupport.lua
It seems some users were relying on the CFBundleVersion format. Reversing back to it for 2021
> Reverting CFBundleVersion to old format

- platform/android/gradle/wrapper/gradle-wrapper.properties
Gradle 6.1 has issue with JDK 14 https://github.com/gradle/gradle/issues/10248
Updating to 6.5 so people can build with JDK 14
> Update gradle to 6.5 for JDK 14

- LICENSE.md
- external/remdebug-1.0/src/controller.lua
- platform/apple/CoronaResources-Info.plist
- platform/mac/CoronaConsole/CoronaConsole/Info.plist
- platform/mac/Credits.rtfd/TXT.rtf
- platform/mac/Info.plist
- platform/windows/Corona.Simulator/Simulator.rc
- sdk/dmg/Corona_License.rtf
- sdk/dmg/Corona_LicenseBeta.rtf
- tools/CoronaBuilder/CoronaBuilder-Info.plist
Just updating the copyright disclaimers.
Related maintenance PR for welcome screen at https://github.com/coronalabs/submodule-welcomescreen/pull/1
> Maintenance: Updating copyright disclaimers

- README.md
Given the Solar2DTux is not being worked on and as it isn't finished, it's best to update the README file accordingly.
> Update README mentions of Solar2DTux

- platform/resources/json.lua
Two global variables lineno and errorMsg were created in json_decode_file
> Remove unnecessary use of global variables

- librtt/Renderer/Rtt_Renderer.h
This is a very tiny fix addressing the problem mentioned [here](https://github.com/coronalabs/corona/issues/397) and further elaborated on in the forum thread linked there. This seems to most affect frequently updated external textures but in theory could affect any new / updating `GPUResource` that was unlucky enough to happen on shutdown.
> LightArrayPtr fix

- platform/windows/Corona.Native.Library.Win32/Interop/UI/RenderSurfaceControl.cpp
- platform/windows/Corona.Native.Library.Win32/Interop/UI/RenderSurfaceControl.h
Some folks in Discord brought up how attempts to stream (using Discord or OBS with the "newest technology", Game Capture sources, etc.) could just blow up on you. The RAM use would climb and climb and the game would then slow and usually crash, whether in simulator or a build.
A couple of us tried to hunt this down. The Vulkan backend seemed robust against it; in the GL backend, it could be "avoided" by commenting out the `SwapBuffers()` calls in the `RenderSurfaceControl`, although at the cost of a black screen. 😃
On a whim, I just commented out the `fPaintDeviceContextHandle` control paths in that class and tried it (from what I could see, the other device context was perfectly good), and everything was suddenly just fine. I'm assuming the streaming hooks get a hold of that `WM_PAINT` …
> (Streaming fix) Use "main" device context exclusively on Windows

- platform/windows/Corona.Native.Library.Win32/Rtt/Rtt_WinTimer.cpp
- platform/windows/Corona.Native.Library.Win32/Rtt/Rtt_WinTimer.h
This is a fix for the issue brought up [here](https://github.com/coronalabs/corona/issues/402). Basically, the simulator will occasionally crash when you relaunch or close.
There's a possibility it's related to [this](https://github.com/coronalabs/corona/issues/186), but that will need some follow-up to confirm. I was testing using a project that did have audio, although I thought it had occurred in quiet ones too. In any case, it wouldn't be unreasonable that audio updates might exacerbate timer issues.
---------------------
**Details**:
Basically, it seems `KillTimer` does not actually evict relevant `WM_TIMER` messages from the queue, in which case they will still fire. There are vague hints of this in some online forum questions, but it's never spelled out. The problem in our case is …
> Windows frame timer fix

- external/lua-5.1.3/src/loslib.c
It turned out the localtime() differs from the standard implementations. The Epoch for NX begin when the device was most recently started. So nx_localtime() is used instead of localtime() for NX.
> Fixing os.time() for NX platform

- platform/android/sdk/src/com/ansca/corona/SystemMonitor.java
Fix for older Android OS's not having "isDeviceLocked" (Android 5<)
> Android: Fix method not found "isDeviceLocked"

- platform/android/sdk/src/com/ansca/corona/CoronaWebView.java
Fix for Issue #287,
There is a slight performance issue with Android WebViews when "alpha" property is used before the page has loaded
See example below
`function showWebView(URL)
local loadingMessage, webView = nil, nil
local x, y = display.safeScreenOriginX + display.safeActualContentWidth/2, display.safeScreenOriginY + display.safeActualContentHeight/2
local function webListener( event )
if event.type == "loaded" then
transition.to( webView, { time = 600, alpha = 1 } )
transition.to( loadingMessage, { time = 400, alpha = 0 } )
end
end
loadingMessage = display.newText({parent = webPopup, text = "LOADING PLEASE WAIT....", x = x, y = y, width = 400, font = native.systemFontBold, fontSize = 15, align = "left"})
webView = native.newWebView( x, y, display.safeActualContentWidth, …
> Android: Fix for performance issue with WebViews

- platform/android/PAD.kts.template
- platform/android/app/build.gradle.kts
- platform/android/settings.gradle.kts
- platform/mac/AndroidAppBuildController.mm
- platform/resources/valid_build_settings.lua
Follows same syntax as [onDemandResources](https://docs.coronalabs.com/plugin/onDemandResources/index.html#project-settings)
Sample code:
```lua
settings =
{
android = {
onDemandResources = {
{ tag = "odr1", resource="sampleUI" },
{ tag = "odr2", resource="rakkann.png", type="install" },
},
},
}
```
> Android/Simulator: option to package for Play Asset Delivery

- platform/windows/Corona.Native.Library.Win32/Rtt/Rtt_WinInputDeviceManager.cpp
In the simulator, _holding_ the up and down keys will slow things down dramatically in Windows. For instance, throw a few emitters out and do so and they'll draw to a crawl.
This seems to concern [this issue](https://github.com/coronalabs/corona/issues/358).
I don't know why only those keys seem to be affected. It did look like they might get hashed deep in their name lookup maps, but that's just a wild guess.
Anyhow, when repeating keys are detected, Solar is just backing out and trying some fallback logic. I don't know if this is necessarily expensive, but it's probably a pretty noisy event.
Since nothing else is going to handle it, it seems enough to mark this as handled and avoid those costs. (The speed increases substantially.) The Android skin / backspace logic seems to be fine, …
> Simulator performance fix: treat repeated keys as handled

- librtt/Rtt_Event.cpp
- librtt/Rtt_Event.h
- platform/mac/AppDelegate.mm
- platform/mac/CoronaShell/CoronaShell/AppDelegate.m
- platform/windows/Corona.Native.Library.Win32/Interop/RuntimeEnvironment.cpp
Event name: `windowState`
Event data: `phase` is either `"foreground"` or `"background"`. 
```lua
Runtime:addEventListener( "windowState", function(e)
if e.phase == "foreground" then
-- do something when activating
elseif  e.phase == "background" then
--- deactivate stuff not needed in background
end
end )
```
> macOS/Windows: adding new windowState event to indicate that window was activated/deactivated

- modules/json/external/dkjson.lua
> Fix json keyorder bug

- external/ALmixer/Isolated/DirectX.cpp
- external/openal-soft-1.12.854/Alc/alcConfig.c
- librtt/Core/Rtt_Allocator.cpp
- librtt/Rtt_PlatformOpenALPlayer.cpp
- platform/shared/Rtt_SimulatorAnalytics.cpp
- platform/windows/Corona.Simulator/SimulatorView.cpp
- platform/windows/Corona.Simulator/SimulatorView.h
I've been doing some hunting in Debug mode and often when closing a session would trigger an assert in **wincore.cpp, line 1055**. I dug into the MFC code and it led me to this post: <https://microsoft.public.vc.mfc.narkive.com/cGo3iW5V/afxmaphwnd-causing-an-assert-why>.
Following the comments, I did a little further investigation and found that the `CoInitialize(nullptr)` done by the Windows simulator view is never answered by a `CoUninitialize()`. This is supposedly a source of leaks and such.
I had also seen there was a class, `ScopedComInitializer`, intended to address this, so I made that a member of `CSimulatorView` and removed the original call. Per the [CoInitialize docs](https://docs.microsoft.com/en-us/windows/win32/api/objbase/nf-objbase-coinitialize), I used the …
> COM balancing and some fixed leaks

- librtt/Corona/CoronaMemory.cpp
- librtt/Corona/CoronaMemory.h
- librtt/Display/Rtt_ShapeAdapterMesh.cpp
Since the "update from buffers" and "memory policy" are now both in experimental, this amends the first of those to use the policy. (This was tested with a slightly modified version of the MoonNuklear plugin.)
> Use memory policy to update from buffer

- librtt/Display/Rtt_ShapeAdapterMesh.cpp
Whoops, forgot to include the memory header in my last update, and somebody pointed out that it wasn't compiling for him. With this fix it does. :)
> Quick fix for memory header

- librtt/Display/Rtt_DisplayPath.cpp
- librtt/Renderer/Rtt_Geometry_Renderer.cpp
- librtt/Renderer/Rtt_Geometry_Renderer.h
- librtt/Renderer/Rtt_Renderer.cpp
This fixes a minor issue that could crop up if you tried to read an object's format extension data  before assigning any. This was flushed it by reading `_properties` on an object.
Both the block and list are now checked against `NULL` where needed, using a new helper function.
> Fix for corner case where vertex format extension block was present but not the corresponding list

- platform/mac/SkinView.mm
- platform/mac/SkinnableWindow.h
- platform/mac/SkinnableWindow.mm
The support for transparent windows was botched for simulator skins. (These devices are not the target platform, but it seems helpful to provide it.) The `setSkinImage` function wanted an `isTransparent` argument and thus, due to lack of that, was just getting ignored. So skins weren't showing up.
The skin view's opacity was also being set to 0.0 when requesting transparency, so would also be hidden for that reason. Now it's set to a small value (0.125, somewhat arbitrary) so you can still see the skin, just faded.
-------
There are still some compromises, probably unavoidable, versus what you would see in a build:
* Because there is a faded skin behind them, any transparent background parts will be slightly less so
* Opaque parts of the content area stand out where screen dressing would …
> Fix for transparent skinnable windows

- librtt/Display/Rtt_LuaLibGraphics.cpp
- librtt/Display/Rtt_SnapshotObject.cpp
This fixes a bug described [here](https://github.com/coronalabs/corona/issues/418):
The two-argument `ContentToScreen()` is used for convenience when calculating the pixel dimensions of the canvas, since the coordinates would go unused. Unfortunately, that's _meant_ for coordinates, and so it drags any non-0 screen origins into the calculation.
(Snapshots also do this.)
A more minor issue: if `pixelWidth` or `pixelHeight` was provided as a canvas option, but not both, they were ignored.
This also adds a (backward-compatible) shorthand for setting `width` and `pixelWidth` to the same value (ditto height): if `pixelWidth` is provided but not `width`, it will be used for both.
> Some small issues in canvas texture setup

- librtt/Renderer/Rtt_CommandBuffer.h
- librtt/Renderer/Rtt_GLCommandBuffer.cpp
- librtt/Renderer/Rtt_GLCommandBuffer.h
- librtt/Renderer/Rtt_GLGeometry.h
- librtt/Renderer/Rtt_Renderer.cpp
- librtt/Renderer/Rtt_VulkanCommandBuffer.cpp
- librtt/Renderer/Rtt_VulkanCommandBuffer.h
Custom vertex formats introduced a corner case where these broke due to vertex attributes not being set. This control path wasn't followed if there was a VAO, thus Android being where it was discovered.
The relevant information is now passed along with the binding, and done afterward if a format change isn't also due.
> Fix for indexed meshes on Android, related to custom vertex formats

- platform/linux/src/Rtt_Assert.cpp
@bakeinflash I see renames nearby fb4467aae2c955356e516b08fd04e4e01dcf326d rename `Rtt_NINTENDO_ENV` to `Rtt_NXS_ENV`, and 0199bc0b75fd160a3d187e8650219cd8835ffd86 introduced an old name.
Most preprocessors was defined in `librtt/Core/Rtt_Config.h` below `Rtt_NXS_ENV` rather than `Rtt_NINTENDO_ENV` so we should use NXS AFAIK.
> NX: fix obsolete preprocessor condition

- librtt/Renderer/Rtt_CommandBuffer.h
- librtt/Renderer/Rtt_GLCommandBuffer.cpp
- librtt/Renderer/Rtt_GLCommandBuffer.h
- librtt/Renderer/Rtt_GLGeometry.cpp
- librtt/Renderer/Rtt_GLGeometry.h
- librtt/Renderer/Rtt_Geometry_Renderer.cpp
- librtt/Renderer/Rtt_Geometry_Renderer.h
- librtt/Renderer/Rtt_Renderer.cpp
- librtt/Renderer/Rtt_Renderer.h
- librtt/Renderer/Rtt_VulkanCommandBuffer.h
Android  (and maybe web, etc.) doesn't use vertex array objects, due from what I recall to some non-conforming devices. This has frustrated some of the logic behind changing vertex formats, including when to dirty them. And these are the fixes.
The implementation was admittedly a bit gnarly, and I noticed some of it also didn't benefit from living in command land, so where possible I moved logic back into `Rtt_Renderer::Insert()` and friends. I was also able to eliminate two commands entirely, as well as some state that was held between commands.
I'll try to do some further sanity tests tonight, but these now seem to work well both on the Android emulator and my phone: 
[Solar2D4.zip](https://github.com/coronalabs/corona/files/11127314/Solar2D4.zip), …
> Some vertex format logic fixes and streamlining

- platform/mac/GLView.mm
> MacOS: Fix crash with display.capture()

- librtt/Display/Rtt_ShaderData.cpp
I was getting reports of this while doing some other tests in Debug on Windows.
You seem to get two leaks per uniform used by an effect (after first assignment), which I'm guessing belong to the two shader mods. Proper instances cloned off of these were being shuttled into the orphanage and then cleaned up, as expected, but nothing was accounting for the originals.
---
There seemed to be [some awareness of the situation](https://github.com/coronalabs/corona/blob/master/librtt/Display/Rtt_ShaderResource.cpp#L94), but I guess it slipped through the cracks.
> Fix for leak in prototypes' ShaderData

- librtt/Display/Rtt_Display.cpp
- librtt/Display/Rtt_LuaLibDisplay.cpp
We don't want to run "ContentToScreen" with color output because w and h are 1 those could be rounded down to 0 on certain screen sizes.
I also noticed the same crash as with display.capture() some times, rerendering after call seems to fix the issue. Can remove that piece if needed
> Core: Fixes for Display Color Sample

- platform/resources/iPhonePackageApp.lua
- platform/shared/Rtt_PlatformAppPackager.h
- tools/CoronaBuilder/Rtt_AppPackagerAppleFactory.mm
- tools/CoronaBuilder/Rtt_AppPackagerLinuxFactory.cpp
Fixes #577
Issue was that we were removing resources by default, and code-signing before removing them. Changed default no to remove, also added option `includeStandardResources` to iOS builder
> iOS: resolving issue with CoronaBuilder

- platform/iphone/Rtt_IPhoneTextFieldObject.mm
- platform/windows/Corona.Native.Library.Win32/Rtt/Rtt_WinTextBoxObject.cpp
based on issue #370
`
local field = native.newTextField( 50, 150, 220, 36 )
--field.clearButtonMode = "UITextClearButtonModeNever" -- default
field.clearButtonMode = "UITextClearButtonModeWhileEditing"
--field.clearButtonMode = "UITextClearButtonModeUnlessEditing"
--field.clearButtonMode = "UITextClearButtonModeAlways"
`
> iOS: Add Clear Button Mode for iOS

- platform/android/sdk/src/com/ansca/corona/CoronaActivity.java
- platform/android/sdk/src/com/ansca/corona/CoronaRuntime.java
- platform/android/sdk/src/com/ansca/corona/CoronaView.java
- platform/android/sdk/src/com/ansca/corona/graphics/opengl/CoronaGLSurfaceView.java
A couple of my tests for the experimental build were working on the Android emulator (`Pixel_3a_API_31_arm64-v8a`, chosen arbitrarily) but not on an actual device (Neffos x9 or so, v7 architecture I believe).
The `eglConfigChooser()` call was not requesting depth (or stencil) bits, although it seems some drivers are generous.
These modifications let you ask for a depth buffer and it will modify that request accordingly.
At the moment this is a simple "I want it", in which case it gives you a 16-bit depth buffer. (If you request a stencil buffer, which will be 8 bits, it will also throw the 16-bit depth buffer in, since these always seem to go hand-in-hand.)
Perhaps some refinement could follow later, e.g. for 24-bit depth, although it would probably have to query for capabilities or pixel …
> Modifications to use application metadata for depth and stencil buffers

- platform/android/ndk/Rtt_AndroidTextFieldObject.cpp
- platform/android/ndk/Rtt_AndroidTextFieldObject.h
- platform/android/ndk/jni/NativeToJavaBridge.cpp
- platform/android/ndk/jni/NativeToJavaBridge.h
- platform/android/sdk/src/com/ansca/corona/NativeToJavaBridge.java
- platform/android/sdk/src/com/ansca/corona/ViewManager.java
- platform/iphone/Rtt_IPhoneTextBoxObject.h
- platform/iphone/Rtt_IPhoneTextBoxObject.mm
- platform/iphone/Rtt_IPhoneTextFieldObject.h
- platform/iphone/Rtt_IPhoneTextFieldObject.mm
- platform/linux/src/Rtt_LinuxTextBoxObject.cpp
- platform/linux/src/Rtt_LinuxTextBoxObject.h
- platform/mac/Rtt_MacTextBoxObject.h
- platform/mac/Rtt_MacTextBoxObject.mm
- platform/mac/Rtt_MacTextFieldObject.h
- platform/mac/Rtt_MacTextFieldObject.mm
- platform/windows/Corona.Native.Library.Win32/Interop/UI/TextBox.cpp
- platform/windows/Corona.Native.Library.Win32/Interop/UI/TextBox.h
- platform/windows/Corona.Native.Library.Win32/Rtt/Rtt_WinTextBoxObject.cpp
- platform/windows/Corona.Native.Library.Win32/Rtt/Rtt_WinTextBoxObject.h
I was working on a custom pixel art textfield for our game and needed a function that can return the current position of the cursor/selector of a native.textField.
There is a function "setSelection" with which you can set the cursor to a position, but sometimes you just need to know the current position/selection.
So I added the function getSelection below the setSelection function for ios, android, mac and windows.
I've tested all platforms.
I also added support for setSelection for macOs Simulator. There was a Warning before that it's not supported, now it is.
That's how you use it:
`local start, finish = myNativeTextField:getSelection()`
This will return you the cursors/selectors first and last position.
Hope you like it and can add this to a daily build soon, so I can normally use it …
> Added getSelection for native.textField

- platform/android/gradle.properties
> The option setting 'android.enableResourceOptimizations=false' is deprecated. The current default is 'true'. It will be removed in version 8.0 of the Android Gradle plugin.
^ Although the Android Gradle plugin will complain, but afaik Solar2D need to keep the widget resource as-is before found out more practical solution.
> Android: keep resource as is

- platform/resources/dkjson.lua
Fix https://github.com/coronalabs/corona/pull/482, tested with following demo:
```Lua
local json = require("json")
local t = { k1 = 123, k2 = false, k3 = false, k4 = '456' }
local str = json.encode( t, { keyorder = {'k2', 'k1', 'k3', 'k4'} })
print( str )
-- before:  {"k1":123,"k4":"456","k3":false,"k2":false}
-- after:   {"k2":false,"k1":123,"k3":false,"k4":"456"}
```
> fix: json encode not follow keyorder

- librtt/Rtt_Runtime.cpp
- platform/android/app/CMakeLists.txt
- platform/android/app/build.gradle.kts
- platform/android/ndk/Rtt_AndroidPlatform.cpp
- platform/android/sdk/src/com/ansca/corona/AudioRecorder.java
- platform/android/sdk/src/com/ansca/corona/CoronaActivity.java
- platform/android/sdk/src/com/ansca/corona/CoronaEnvironment.java
- platform/android/sdk/src/com/ansca/corona/CoronaSystemApiHandler.java
- platform/android/sdk/src/com/ansca/corona/CoronaView.java
- platform/android/sdk/src/com/ansca/corona/NativeToJavaBridge.java
- platform/android/sdk/src/com/ansca/corona/listeners/CoronaSystemApiListener.java
- platform/android/sdk/src/com/ansca/corona/storage/FileServices.java
This PR contains where
Some typo fixes.
Fix when using the 'Run' button in Android Studio to re-run with a changed Lua project file, the Gradle task does not recognize the changes and **incorrectly** marks mergeDebugAssets as `UP-TO-DATE`, this cause App remain unchange.
This is a temporary solution to facilitate debugging of Android applications by Solar2D engine maintainers, and Gradle tasks should be reorganized in the future.
Adjust buffer sizes that are more friendly to memory paging and I/O throughput. 64KB size vs. the original 1KB, using FileService#getBytesFromFile() reading 100MB (unflatten) of `resource.car` is at least a 10% improvement on the Pixel 7 and 30% on the Galaxy S7 edge.
Additionally, in the future, it will be necessary to change the way Android reads Lua code …
> Android maintenance

- platform/iphone/Rtt_IPhonePlatformCore.mm
> iOS: Fix for display.save saving black image on iOS 17+

- librtt/Core/Rtt_Data.h
- librtt/Display/Rtt_LuaLibGraphics.cpp
- platform/android/app/build.gradle.kts
- platform/android/ndk/jni/NativeToJavaBridge.cpp
- platform/android/sdk/src/com/ansca/corona/storage/ZipResourceFile.java
> Does it make sense to add these checks in the case of OOM? Should we "fix" these boundary cases? Or should we just expose them to expose the game code error?
> 
> ^These questions bother me, but I'm willing to give it a try, so if the changes don't fit please feel free to discuss.
These fixes come from analyzing the OOM crash stack, enhancing some of the checks.
These changed stack contents in cases where an error had already occurred.
Regarding`Data.Set()`, it is envisioned that in the OOM case, fLength retains a non-zero value even if fStorage is empty. It is good practice to perform a `Data.Get()` check before using it.
Of course, there's also an Android `build.gradle.kts` issue where switching `coronaSrcDir` causes the previous project's `resource.car` content to be incorrectly …
> Core/Android: add sanity check

- .github/workflows/build.yml
This PR try to fix `node@20` not being updated with the `icu4c` upgrade, on the Solar2D side. Related to https://github.com/coronalabs/corona/pull/680.
GitHub Action on tag 3705 macOS part failed, the [error](https://github.com/coronalabs/corona/actions/runs/8226561621/job/22495198727#step:21:26146) shows as below, `node@20 (20.11.1)` look for `icu4c 73.2 (libicui18n.73.dylib)` in `74.2` path `/usr/local/Cellar/icu4c/74.2`:
```shell
+ appdmg sdk/dmg/processed_appdmg.json Corona-2024.3705.dmg
dyld[36835]: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.73.dylib
Referenced from: <0E183B51-9141-3D2F-B2F4-A5607A6ECA41> /usr/local/Cellar/node@20/20.11.1/bin/node
Reason: tried: '/usr/local/opt/icu4c/lib/libicui18n.73.dylib' (no such file), …
```
> Maintenance Action about node and icu4c

- librtt/Rtt_Archive.cpp
- librtt/Rtt_Archive.h
- librtt/Rtt_LuaProxyVTable.cpp
- librtt/Rtt_Runtime.cpp
- platform/android/sdk/src/com/ansca/corona/CoronaActivity.java
- platform/android/sdk/src/com/ansca/corona/storage/FileServices.java
This PR removes a main thread IO to avoid ANR; allows Android to use mmap to load Lua code packages; and an additional Rtt_ASSERT correction.
There is a risk of ANR when `loadExpansionFiles()` in the main UI thread, so the main UI thread reading is changed to the main thread modifying the state, and the GLThread is used to read.
This PR allows Android to load the Lua code package (resource.car) like other platforms, using mmap, to reduce runtime memory by extracting the resource.car at first launch. It doesn't need to be uncompressed every launch, so it also positively affects startup time.
During the public beta phase, it was observed that some models showed the situation where `AssetManager` prematurely returns -1 when decompressing resources (approximately 0.3%). This issue was …
> Android: avoid main thread io and mmap the resource.car

- .github/workflows/build.yml
Supplementary submission of https://github.com/coronalabs/corona/pull/681.
Rechecked the update content and found that [download-artifact no longer creates a directory for artifacts by default](https://github.com/actions/download-artifact/tree/v3.0.2?tab=readme-ov-file#compatibility-between-v1-and-v2v3).
Also checked the changes currently in use but compatible content:
> Maintenance adapt actions upload&download to v4

- platform/android/sdk/src/com/ansca/corona/notifications/NotificationServices.java
SCHEDULE_EXACT_ALARM, the permission introduced in Android 12 for apps to schedule exact alarms, is no longer being pre-granted to most newly installed apps targeting Android 13 and higher (will be set to denied by default).
And because the SCHEDULE_EXACT_ALARM permission is now denied by default and the permission grant process requires extra steps from users (the user must minimize the application and change the setting), developers are strongly encouraged to evaluate their use cases and determine if exact alarms still make sense for their use cases.
Now for Android devices with SDK greater than or equal to 33, a check has been added for the ability to schedule notifications via AlarmManager.setExactAndAllowWhileIdle(). If this is not possible, then the notification is sent via …
> Added check to exact scheduling for notifications

- librtt/Display/Rtt_LuaLibGraphics.cpp
Use the sample project [LiquidFun-ColorGroup](https://github.com/coronalabs/samples-coronasdk/tree/93e6a10650c3379850e63dc008ae3d94c5d29c9b/Physics/LiquidFun-ColorGroup) and make the following modifications, which results Android and macOS Simulator to crash on 3706:
```diff
-72 local image_outline = graphics.newOutline( 1, "outline.png" )
+72 local image_outline = graphics.newOutline( 1, "outline1.png" )
```
This PR avoid [graphics.newOutline()](https://docs.coronalabs.com/api/library/graphics/newOutline.html) crash when image not found, just cause the *object* not to created/display.
> Core: fix newOutline crash when image not found

- platform/resources/CoronaPListSupport.lua
- platform/resources/OSXPackageApp.lua
- platform/resources/iPhonePackageApp.lua
- platform/resources/tvosPackageApp.lua
i.e
```
iphone =
{
xcassets = "Images.xcassets",
plist =
{
UILaunchStoryboardName = "LaunchScreen",
CFBundleIdentifier = "com.appodeal.sandbox",
NSAppTransportSecurity = { NSAllowsArbitraryLoads=true },
},
xcprivacy = {
NSPrivacyAccessedAPITypes = {
{
NSPrivacyAccessedAPIType = "NSPrivacyAccessedAPICategoryFileTimestamp",
NSPrivacyAccessedAPITypeReasons = { "3B52.1"}
}
}
},
},
```
> Apple: Privacy Settings Support

- platform/android/ndk/Rtt_LuaLibOpenSLES.cpp
The _metatable_ for Android `audio2` overwrites the _metatable_ for `audio`, causing the following properties (obtained by ___index_) to get incorrectly:
```Lua
audio.freeChannels
audio.unreservedFreeChannels
audio.usedChannels
audio.unreservedUsedChannels
audio.totalChannels
audio.reservedChannels
audio.supportsSessionProperty
```
And an error prints:
```Plain
Unsupported key: supportsSessionProperty in audio library
```
when obtaining the `supportsSessionProperty` instead of return `false`:
```Lua
if supportsSessionProperty == true then
audio.setSessionProperty(audio.MixMode, audio.AmbientMixMode)
end
```
---
AFAIK, there should be no side effects other than affecting the acquisition of the above properties.
**However, it is still necessary to be cautious about merging, because it is …
> Android: fix audio metatable being covered

- platform/iphone/Rtt_IPhonePlatform.mm
- platform/iphone/Rtt_IPhonePlatformBase.mm
" BUG IN CLIENT OF UIKIT: The caller of UIApplication.openURL(_:) needs to migrate to the non-deprecated UIApplication.open(_:options:completionHandler:). Force returning false (NO)."
Based on forums
https://forums.solar2d.com/t/on-ios-18-system-openurl-url-does-not-work/356845/2
> iOS: Fixes to Open Url for iOS 18

- platform/mac/AppleSigningIdentityController.h
- platform/mac/AppleSigningIdentityController.mm
Based on 
https://forums.solar2d.com/t/installing-a-provisioning-profile-with-xcode-16-0-doesnt-work/356864/9
> Apple: Scan new Xcode Provision Directory

- platform/emscripten/Rtt_EmscriptenContext.cpp
I have implemented this sample a few months ago, and it works well with various projects.
https://github.com/kan6868/s2d-html-template
- Fixing blurry images:
I enlarged the game content by double and then reduced the canvas size by half.
```c++
// keep ratio
float scaleX = (w * 2) / (float)fWidth;
float scaleY = (h * 2) / (float)fHeight;
//reduced canvas size
emscripten_set_element_css_size("canvas", w / 2, h / 2);
```
- Fixing FPS flow issues: 
Based on this #699 
- Fixing crashes when zooming: 
I realized that at certain screen sizes, the width or height values of the content would return 0. So, I reassigned them.
```c++
if (w == 0 || h == 0) 
{
w = jsContextGetWindowWidth();
h = jsContextGetWindowHeight();
}
```
> [HTML5] Fix blurry, low FPS and crash when zooming.

- platform/android/sdk/src/com/ansca/corona/NativeToJavaBridge.java
https://forums.solar2d.com/t/saving-images-to-the-gallery-hasn-t-been-working-since-android-10-display-capturebounds/356924
Android seems to lock out writing directly to Camera Roll on 10+
> Android: Save Photos to Library on Android 10+

- platform/android/sdk/src/com/ansca/corona/NativeToJavaBridge.java
Fix issue #733 .
In Android 10 (API level 29) and above, Google introduced Scoped Storage, which changed how applications access external storage. To save images to the gallery, we now need to use the MediaStore API.
> [Android] Fix `media.save()`.

- tools/CoronaBuilder/BuilderPluginDownloader.lua
Some of my plugins don't need extra Frameworks for Native Build
(i.e my Game Center Plugin)
> Native: Fixes To Plugin Downloader for iOS

- librtt/Rtt_LuaLibSystem.cpp
Back with the Merging of the experimental branch merger it removed haptic support(see photo), this commit adds it back
> iOS/Android: Add Haptic Support Back

- librtt/Renderer/Rtt_GLCommandBuffer.cpp
Versions >= 3713 stream some smaller-than-`int` data to `GLCommandBuffer`: `bool` in the FBO case, and then there are `U16`s elsewhere. _Some_ platforms seem to be choking on the unaligned reads that result.
This is the fix posted in #760. I suspect it's also what #751 is about&mdash;captures and snapshots both touch FBOs&mdash;but still waiting on word there.
This replaces the `reinterpret_cast` + dereference with a (fixed-size, per template instantiation) `memcpy()`. From various C++ discussions I've followed it sounds like all the compilers we use will do the obvious (safe) peephole optimization here.
> Fix for unaligned reads

- librtt/Renderer/Rtt_Renderer.cpp
This one-liner is, I hope, the fix for [this issue](https://forums.solar2d.com/t/release-3713-will-not-build-html5/357035/10).
---
The new stuff in 3713 introduced custom vertex formats. These meant you could no longer always jump right into the geometry data, and thus need a "correction": `fVertexOffset - fOffsetCorrection`, in `Renderer::CheckAndInsertDrawCommand()`.
The "stored on GPU" path would still want essentially the old behavior, since its buffers only have data for themselves, but the correction snippet was still being used, but never zeroing out that value: it's either whatever it last was or (as in the link) some uninitialized garbage. In the latter case that happens to be a negative value and thus produce that WebGL error.
---
This was a general bug&mdash;I believe I _did_ …
> Reset offset correction in "stored on GPU" path

- platform/resources/iPhonePackageApp.lua
Adding the ability for iOS Apps to support appx files in their apps. This could be used to support any of the following extensions via the plugin system:
Widgets, Intents, iMessage, etc
https://developer.apple.com/app-extensions/
Note that my main use for this at the moment is to support Rich Notification Extensions for an upcoming Personal Plugin for OneSignal for Corona Sim.
I will write some basic docs for this in Corona Native/ Corona Sim guides for how to support this.
I updated the signing script to sign the Appx/Extensions if there are any plugins; include them appropriately. 
Thanks,
Scott
> iOS: Support for Extensions

- bin/mac/CreateInfoPlist.sh
- bin/shared/Compile.lua
- platform/mac/CoronaBuilder.xcodeproj/project.pbxproj
- platform/mac/CoronaShell/CoronaShell/Base.lproj/MainMenu.xib
- platform/mac/build_native.sh
- platform/mac/car.xcodeproj/project.pbxproj
- platform/mac/lua.xcodeproj/project.pbxproj
- platform/mac/plugins.xcodeproj/project.pbxproj
- platform/mac/ratatouille.xcodeproj/project.pbxproj
- platform/resources/CoronaPListSupport.lua
I have been building been working with a client to do Solar2D Mac App building from Xcode, I still need to post a template to support this, but I basically put a copy of CoronaCards for Mac in native folder(under Mac) and tweak the lua output from the compiler path for Native Mac Building.
This also includes support to build MacOS Sim on Apple Silicon natively and locally
> Native: MacOS Xcode Building Support

- librtt/Corona/CoronaGraphics.h
- librtt/Corona/CoronaMemory.h
- librtt/Corona/CoronaObjects.h
- librtt/Corona/CoronaPublicTypes.h
@kan6868 and I have been working on a [Tiny C compiler](https://www.bellard.org/tcc/) plugin.
To be useful, it's hooked up to Solar's "Corona" and "lua" headers.
This being a _C_ compiler, it got tripped up by a few C++-isms I let slip into previous PRs. These pretty much all involve little `typedef` goofs.
With these edits the plugin works well. (At the moment the plugin points to copies of the headers with these same fixes.)
> Made some headers C-friendly

- bin/mac/CreateInfoPlist.sh
- bin/mac/buildSettingsToPlist.lua
- tools/CoronaBuilder/BuilderPluginDownloader.lua
Add option for Native TvOS build support build.settings to plist generation (before was using pulling iOS/iPhone plist settings)
i.e with "$CORONA_ROOT"/Corona/mac/bin/CreateInfoPlist.sh --tvOS
> Native: TvOS build.settings support

- librtt/Renderer/Rtt_GLTexture.cpp
@ggcrunchy and I discussed how [Rtt_GLTexture](<https://github.com/coronalabs/corona/blob/d2b6a4fa960a827cabf4de5f756e1c653a439e46/librtt/Renderer/Rtt_GLTexture.cpp#L144>) pixel packaging is quite broken, causing the weird "multiple of 4" mask rule.
Additionally, if the texture width isn’t divisible by 4 and format texture is RGB, OpenGL automatically adds padding at the end of each row, which leads to display bugs in the last line of pixels in [bytemap](<https://github.com/solar2d/com.xibalbastudios-plugin.Bytemap>) plugin.
After fixing this issue, it now works correctly with masks of any size, even those not divisible by 4.
> Fixing unpack with alignment 

- platform/emscripten/Rtt_EmscriptenContext.cpp
- platform/emscripten/gmake/build_app.sh
- platform/emscripten/gmake/template.webapp/emscripten-nosplash.html
- platform/emscripten/gmake/template.webapp/emscripten.html
- Some improvements to make the build work well on mobile.
- Remove LEGACY_VM_SUPPORT Because it is no longer needed.
- Enable Vsync.
- Scale the init config value with devicePixelRatio.
[Alecgames](<https://www.alecgames.com/>) has had some good games built on this PR, here is an example.
It works well on both PC and Mobile.
https://effulgent-malasada-e96974.netlify.app/
Test with this [webtemplate.zip](https://github.com/user-attachments/files/21085154/webtemplate.zip)
> [HTML5] Enable Vsync, optimize CSS for mobile.

- librtt/Rtt_LuaLibPhysics.cpp
Add **Circle** shape with 2 parameters x, y. It works fine with **radius**.
```lua
physics.addBody(object, "dynamic", 
{ radius = 32 },
{ box = { halfWidth = 24, halfHeight = 50, x = 2, y = -50 } },
{ circle = { radius = 52, x = 0, y = -140 } }
);
```
> Add x, y offset to circle physics body.

- platform/android/sdk/CMakeLists.txt
The ndk version used in solar2d is 18.1.5063045. According to [this doc](https://developer.android.com/guide/practices/page-sizes?ndk-build=#compile-r22-lower), we should set these two flags:
`-Wl,-z,max-page-size=16384 -Wl,-z,common-page-size=16384`
I found that it's not necessary to set flags in every relevant CMakeLists.txt file; just in "platform/android/sdk/CMakeLists.txt".
See the related issue #820  that this pull request solved.
> Fix 16KB support in old ndk version(18.1.5063045).

- platform/linux/src/Rtt_LinuxContext.h
- platform/linux/src/Rtt_LinuxSimulator.cpp
- platform/linux/src/Rtt_LinuxSimulator.h
Added Rotate Left and Right. #834 was not a complete solution because it was making vertical orientation horizontal and vice versa.
> Linux: Rotate left and right added

- .github/workflows/build.yml
- platform/mac/AppDelegate.mm
- tools/CoronaBuilder/BuilderPluginDownloader.lua
- tools/buildsys-ios/libtemplate/Defaults.lua
I bumped up support for Xcode 26, iOS and MacOS
Note that -ld_classic is not longer need and including it leads to the following error when building
[ld: Assertion failed: (it != _dylibToOrdinal.end()), function dylibToOrdinal, file OutputFile.cpp, line 5184](https://stackoverflow.com/questions/79677312/ld-assertion-failed-it-dylibtoordinal-end-function-dylibtoordinal-fi)
> Apple: iOS and MacOS 26 support
